# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('osver', models.CharField(max_length=50)),
                ('sn', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('cpu_num', models.IntegerField()),
                ('cpu_model', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
    ]
